version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /home/ssg/app/node_modules
      - ./:/home/ssg/app
    stdin_open: true
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/ssg/app/node_modules
      - ./:/home/ssg/app
    command: ["npm", "run", "test"]